### ISSUE TITLE
missing labels from drop down

### ISSUE THREAD

**Issue by daniellemiller** [burstein-lab/genomic-nlp-server#131]
possible bug, Prokaryotic defense, and secretion systems are not available on the "Label" search.

**Comment by daniellemiller** [comment]
not a bug in the data (hurray)!!
@notofir - search by label using labels at `label_to_word.pkl` (hope this is thee write ref)

https://github.com/burstein-lab/genomic-nlp-server/blob/7a2b920191aefa5b8063995bdd61f62938e2e5d0/server/app.py#L157-L159

**Comment by notofir** [comment]
It happens because of misuse of LABEL_TO_WORD - when searching it currently looks up the exact key (map lookup), but we need to search it in the keys instead (df lookup `contains` for example).
