### ISSUE TITLE
Add color mapping legend

### ISSUE THREAD

**Issue by daniellemiller** [burstein-lab/genomic-nlp-server#147]
color to function mapping legend:
add a color bar with a title: **Functional Category**
@notofir let's talk about HOW in the meeting.

**Comment by daniellemiller** [comment]
search for options to represent the legend of > 100 categories. 
if nothing useful is found just look for a place to add a comment, points are color-coded by functional group

**Comment by notofir** [comment]
@daniellemiller , can we close this?

**Comment by daniellemiller** [comment]
let's close with @dudubur today how to write it down in the app without legend.
"dots are color coded by functional category"?
