### ISSUE TITLE
fixed color when choosing label

### ISSUE THREAD

**Issue by daniellemiller** [burstein-lab/genomic-nlp-server#148]
when searching by label, each time a user chooses a label the color of the highlighted dots changes.
make the selection colored fixed, to allow easy distinction of selected categories:

for `n` possible selections (define `n=10`, i.e., no more then 10 categories were selected simultaneously) 
colors will be: 

`colors: 
['#35ada1',
 '#38a9c1',
 '#5f9df4',
 '#c47ef4',
 '#f564d3',
 '#f77090',
 '#e28532',
 '#b29b32',
 '#7fa931',
 '#33b173']`
 
such that ith selected category will have the ith elements in `colors`

 color palettes were generated by seaborn:
`sns.husl_palette(h=.5, n_colors=10).as_hex()`

**Comment by dudubur** [comment]
relevant for KO multiple selections.
When choosing multiple KOs iterate over the list of colors Miller provided :)

**Comment by notofir** [comment]
@daniellemiller , can we close this?

**Comment by daniellemiller** [comment]
yes.
