### ISSUE TITLE
Add hover data on predicted neighbors  

### ISSUE THREAD

**Issue by daniellemiller** [burstein-lab/genomic-nlp-server#149]
for each word in the neighbor's barplot add the same hover data as in the space map (using `model_data.pkl`.)

https://github.com/burstein-lab/genomic-nlp-server/blob/a6d5c24a46142b6574d71a4058d8f429b56956e5/web/src/composables/spaces.ts#L61-70

**Comment by dudubur** [comment]
Hover on the bar plot - see in addition to identifier, also point information (as when focusing on a point in the map)
