### ISSUE TITLE
search by label can cause weird change in point border color

### ISSUE THREAD

**Issue by daniellemiller** [burstein-lab/genomic-nlp-server#150]
when selecting a label (Antibiotic resistance), the square of points appear:

<img width="551" alt="image" src="https://user-images.githubusercontent.com/21245005/229476616-b8e41bbd-fba9-4489-912f-ca76304126b2.png">

after zooming in some of the points with blue borders became grey following a mouse hover: 
<img width="656" alt="image" src="https://user-images.githubusercontent.com/21245005/229476927-d4268869-7db2-43fe-87be-8566b50d5e6d.png">

**Comment by notofir** [comment]
Doesn't reproduce.

**Comment by dudubur** [comment]
transferred to other zoom issue
