### ISSUE TITLE
generate g2v files instead of the matrix for faster neighbors calculation

### ISSUE THREAD

**Issue by notofir** [burstein-lab/genomic-nlp-server#161]
We will load the data from static files / DB instead of loading the 1GB matrix.

**Comment by daniellemiller** [comment]
made a PR #165  for the script generating all files.
it is `SUPER` slow, so I have already calculated all file as uploaded into gcp under knn.tar.gz
name of the file corresponds to `word` and the content is a txt file with: `word<whitespace>score`
