### ISSUE TITLE
Wiki++

### ISSUE THREAD

**Issue by dudubur** [burstein-lab/genomic-nlp-server#163]
@daniellemiller 
1. Add real-life usage  
2. Show the 
    👩‍🔬 Explanatory mode
    🔬 Predictive mode
on the main page so it is evident what a nice wiki we have.

**Comment by daniellemiller** [comment]
closed with [922f5bd](https://github.com/burstein-lab/genomic-nlp-server/commit/922f5bd7ec84554d7c57ae9abf062ee4f5d1f9b7)
