### ISSUE TITLE
change gene prediction scatter plot hover data

### ISSUE THREAD

**Issue by daniellemiller** [burstein-lab/genomic-nlp-server#172]
for hypothetical proteins with gene prediction` scatter plot option change each point hover data:
`class name: value`, where class name is the name of the functional category in the x-axis and value is the y-axis value.

**Comment by notofir** [comment]
Didn't understand the issue :(

**Comment by daniellemiller** [comment]
I think it is referring the following: 
https://github.com/burstein-lab/genomic-nlp-server/blob/090cfe3a8d3d007413c23b723adf08cbf2a2c65f/server/app.py#LL92C1-L98C6
