### ISSUE TITLE
tooltips for Focus and Dark/Light mode

### ISSUE THREAD

**Issue by dudubur** [burstein-lab/genomic-nlp-server#173]
When Hooovering over the focus and dark/light mode buttons, add a small tooltip.

**Comment by notofir** [comment]
what tooltip?

**Comment by dudubur** [comment]
When you hoover over the purple dark/light switch mode, can we have a small tooltip saying "dark/light mode" and when hoooovering over the nice new purple focus button have a tooltip saying "focus".

Or something like that....
