### ISSUE TITLE
change "Space" search mode results

### ISSUE THREAD

**Issue by daniellemiller** [burstein-lab/genomic-nlp-server#188]
change Space search mode in dropdown to include `MODEL_DATA` column `KO` with all NA excluded.

**Comment by notofir** [comment]
What should I do with current cases? i.e. "." in name.
![image](https://github.com/burstein-lab/genomic-nlp-server/assets/7872989/09f4818c-3a0b-4345-9a3a-da7dcea0e81e)

**Comment by daniellemiller** [comment]
there won't be any selection possible with a "." in the KO columns, in past versions we had two columns to inspect - now we have only one.
enable in selection only names in MODEL_DATA.df["KO"]
