### ISSUE TITLE
Show DIAMOND results for first hit

### ISSUE THREAD

**Issue by daniellemiller** [burstein-lab/genomic-nlp-server#191]
when DIAMOND finishes in addition to download results add below the input sequence panel the information on the **first hit** in the database.
show the following fields (after "-" the name of the field presented to the user) :
1. query - `Query`
2. word - `Word`
3. e-value - `E-value`
4. identical_amino_acid_percentage - `Percent Identical`

**Comment by notofir** [comment]
WDYM first hit? If someone queries two sequences, should I present the first one only? Or should I present the first result for each query? Do we get more than one result per query?

**Comment by daniellemiller** [comment]
we allow only one hit per sequence, and yes - show the first one only (if someone searched for 5 sequences he will be able to download all results )

**Comment by daniellemiller** [comment]
I think only the first one as a request for 10-12 genes by a user can lead to a visual mess :)
