### ISSUE TITLE
Some typos / grammar

### ISSUE THREAD

**Issue by guyshur** [burstein-lab/genomic-nlp-server#196]
....

NOTICE: This process might take **_a_** few minutes 🤗

...

The highlighted dot on the space **_marks_** hypo.clst.15503442. By zooming in to the cluster in which this dot **_resides_** we can **_interactively_** **_inspect_** the neighboring genes, most of **_which_** are related to the CRISPR-Cas system. **_For an_** in depth **_analysis_**, click on the dot to open a panel with the following information:

  
The predicted class is Prokaryotic Defense System and the prediction is reliable (trusted prediction is True).
By clicking on GENE PREDICTIONS a panel will open showing all scores **_received_** by the model for the different classes. Here, the Prokaryotic Defense System prediction was unequivocal, with a score closed to 1 (possible scores are between 0 to 1).

...

This **_strengthens_** the **_confidence_** that this protein is related to **_d_**efense mechanisms, and more specifically to Subtype I in which Csc proteins are apparent.

note: distances were calculated on a high dimensional space, thus **_elements_** might not seem to be close in the 2D space map.

**Comment by dudubur** [comment]
@daniellemiller

**Comment by daniellemiller** [comment]
closed as completed by [#922f5bd](https://github.com/burstein-lab/genomic-nlp-server/commit/922f5bd7ec84554d7c57ae9abf062ee4f5d1f9b7)
