### ISSUE TITLE
Hard to tell apart selected/unselected genes in maximal zoom

### ISSUE THREAD

**Issue by guyshur** [burstein-lab/genomic-nlp-server#199]
It is difficult to tell which genes are transparent/opaque at maximal zoom, especially for the visually impaired. Perhaps consider highlighting selected genes further with wider/colorful borders in increasing transparency of unselected genes?
![opacity](https://github.com/burstein-lab/genomic-nlp-server/assets/50172548/0df05209-da6c-447c-8925-d7b1f85072de)

**Comment by dudubur** [comment]
looks ok to me now
