### ISSUE TITLE
"No significat hit was found in the database." for a sequence input without an identifier

### ISSUE THREAD

**Issue by guyshur** [burstein-lab/genomic-nlp-server#200]
When using the example sequence without an identifier (simply copying MTKLELLVSVMVDGKWYSTDDLVSRVGHRFSATKHVAEKQGYQFEKRREGMRFEYRMVSTTIELAR into the search box and clicking the arrow) it gives the message "No significat hit was found in the database.". I understand that the example implicitly showing that identifiers are required, but perhaps make it a bit clearer and explicit in the guide, or better yet, give a better message if the input is malformed, or even allow entering sequences without identifiers?

**Comment by notofir** [comment]
Resolved by d51945f
