### ISSUE TITLE
Problem searching by Gene description

### ISSUE THREAD

**Issue by dudubur** [burstein-lab/genomic-nlp-server#222]
Searching, for example, **Gene description** for `IcmW` gives in the menu `intracellular multiplication protein IcmW`, but searching for it gives nothing.
On the other hand, when searching **Gene name** for `icmw` quickly and nicely gives a result (K12224.1)

**Comment by notofir** [comment]
Implementation seems to be ok according to: #193

**Comment by notofir** [comment]
@daniellemiller
