### ISSUE TITLE
reset button as refresh?

### ISSUE THREAD

**Issue by daniellemiller** [burstein-lab/genomic-nlp-server#229]
remove all data from search modes and refresh the page completely?

what do you think? @dudubur

**Comment by dudubur** [comment]
Agreed! 
Ofir solved a similar issue about refresh, which solved most things, but it seems the search info still stays.

**Comment by notofir** [comment]
I disagree with complete refresh of the page - there's already a button for this in the browser itself...
IMO we should fix anything that you see that isn't being reset, or simply remove this button.
