### ISSUE TITLE
add snack bar for "neighbors" option 

### ISSUE THREAD

**Issue by daniellemiller** [burstein-lab/genomic-nlp-server#233]
Add an icon + warning for all options related to "Neighbors":
1. dropdown search bar - below the search bar
2. interactive barplot NEIGHBORS - above the barplot

This is the warning: "Distances were calculated on high dimensional space and might differ in the two-dimensional projection"

**Comment by dudubur** [comment]
The original high-dimensional distances may look different in the two-dimensional representation.
