### ISSUE TITLE
Clear results between search

### ISSUE THREAD

**Issue by dudubur** [burstein-lab/genomic-nlp-server#235]
For example when searching for Functional category "ABC transporters" and then searching for Functional category "Amino acid metabolism" the dots belonging to both categories are marked (yellow and green in the print screen below):
![image](https://github.com/burstein-lab/genomic-nlp-server/assets/67689371/e6809df3-cc87-44d2-8f92-24d3e5842e84)

**Comment by daniellemiller** [comment]
@notofir TOP PRIORITY
