### ISSUE TITLE
reduce number of points threshold for faster zoom-in

### ISSUE THREAD

**Issue by daniellemiller** [burstein-lab/genomic-nlp-server#246]
Enhance performance of pointing interactive points by:
* create static tiles for zoom higher zoom-in levels
* add a threshold for the number of points for plotting in interactive mode - need to explore the number: 500\ 1000? 

reviewer 1 suggested datashader to improve performance, can take a look if needed (https://datashader.org/)

**Comment by notofir** [comment]
Resolved by #253
