### ISSUE TITLE
add whole data gene counts in the information bar

### ISSUE THREAD

**Issue by daniellemiller** [burstein-lab/genomic-nlp-server#264]
for each word (point in space) add in the information bar its gene count.
the new field should appear under Functional category as `Gene family count`

the gene counts should be taken from MODEL_DATA column `word_count`

<img width="519" alt="image" src="https://github.com/burstein-lab/genomic-nlp-server/assets/21245005/1ca4cc44-736f-48d1-9c49-bcecf553df57">

**Comment by notofir** [comment]
Should neighbors tsv and diamond result include this field?
