### ISSUE TITLE
update readme, wiki and supp

### ISSUE THREAD

**Issue by daniellemiller** [burstein-lab/genomic-nlp-server#267]
update readme with new features:

- tax info graph
- all new screenshots? @dudubur

**Comment by dudubur** [comment]
Let's do new screenshots when we have everything sealed.

**Comment by daniellemiller** [comment]
* add a line for unavailable TAX MAP when a gene family is found only in metagenomes.
* verify this extension in the text 
* Update Figure 1 with space when colors are final
