### ISSUE TITLE
Broken links to genome.jp

### ISSUE THREAD

**Issue by notofir** [burstein-lab/genomic-nlp-server#273]
In regard with #265 - I found that "CRISPR" isn't considered hypothetical. This results in a broken link to https://www.genome.jp/entry/CRISPR
![image](https://github.com/burstein-lab/genomic-nlp-server/assets/7872989/31eaad08-b03e-46f5-8d9b-3aea3f5b0e7c)

**Comment by daniellemiller** [comment]
we have a few exceptions that will not have any link:
CRISPR
tRNA
rRNA
tmRNA

just leave N/A instead of link for those.
