### ISSUE TITLE
Gene count in family -1

### ISSUE THREAD

**Issue by dudubur** [burstein-lab/genomic-nlp-server#284]
hypo.clst.6574650 has gene count in family -1 
maybe there are others

**Comment by dudubur** [comment]
hypo.clst.11838434 is another one.
These also do not have TAX MAP.
![giphy-downsized 1](https://github.com/burstein-lab/genomic-nlp-server/assets/67689371/e9d1a0a0-7977-4ea9-8da9-423410895650)

**Comment by daniellemiller** [comment]
@dudubur not all words have a TAX MAP (some are found only in the metagenomics datasets).
re family size -1: an updated version is now on GCP @notofir can you pickle-unpickle and update?

**Comment by dudubur** [comment]
Could we have a notice like "Found exclusively in metagebomics" for those without a tax map?

**Comment by dudubur** [comment]
resolved by uploading a new data frame
