### ISSUE TITLE
Color order

### ISSUE THREAD

**Issue by notofir** [burstein-lab/genomic-nlp-server#285]
https://github.com/burstein-lab/genomic-nlp-server/issues/275#issuecomment-1817892132

> @notofir color order:
> ['#808080', '#6a3d9a', '#a6cee3', '#ff1493', '#ffd700', '#00ced1', '#808080',
>        '#ff9933', '#1f78b4', '#fb9a99', '#e6e6fa', '#b2df8a', '#ffff99',
>        '#b15928', '#e31a1c', '#ffff00', '#33a02c']
> Im plotting with some opacity, just not to run over all points, we can try but not mandatory.

Fixed order:
['#808080', '#6a3d9a', '#a6cee3', '#ff1493', '#ffd700', '#00ced1',
       '#ff9933', '#1f78b4', '#fb9a99', '#e6e6fa', '#b2df8a', '#ffff99',
       '#b15928', '#e31a1c', '#ffff00', '#33a02c']

**Comment by notofir** [comment]
@daniellemiller, is `#808080` first, or last?

**Comment by dudubur** [comment]
This is the order for plotting the dots such that #808080 is plotted first

**Comment by daniellemiller** [comment]
`#808080` first
