### ISSUE TITLE
TAX MAP "other" => Grey

### ISSUE THREAD

**Issue by dudubur** [burstein-lab/genomic-nlp-server#288]
Let's make the "other" category in TAX MAP always grey.

**Comment by notofir** [comment]
WDYM? When is it not grey?

**Comment by dudubur** [comment]
When there are fewer than the max orders allowed. example below
![image](https://github.com/burstein-lab/genomic-nlp-server/assets/67689371/821092b8-c8cf-4666-a8c1-4e13f2b1e84f)
