### ISSUE TITLE
Do not use "other" in TAX MAP legend if there is no other label

### ISSUE THREAD

**Issue by dudubur** [burstein-lab/genomic-nlp-server#295]
In some cases, it seems that there are no "other" in TAX MAP, yet it still appears in the legend (2 examples below):
<img src="https://github.com/burstein-lab/genomic-nlp-server/assets/67689371/8155a921-47e1-440e-9de8-051ff7ad650d" width="250">

<img src="https://github.com/burstein-lab/genomic-nlp-server/assets/67689371/ceead7e3-51ac-49a8-8237-321ea9fc6c99" width="250">

**Comment by notofir** [comment]
I think it's best to remove it from model_data.

**Comment by dudubur** [comment]
Seems to still have Other in the legend when there is no other, for example in hypo.clst.2689073:


![image](https://github.com/burstein-lab/genomic-nlp-server/assets/67689371/adcc5c00-c8af-4bad-b3c2-1d998fa96650)
