### ISSUE TITLE
Color swap (legend and dots)

### ISSUE THREAD

**Issue by dudubur** [burstein-lab/genomic-nlp-server#305]
@notofir 
Can we please change the following colors:
change `#a6cee3` to  `#ffc067`
change `#ffff00` to `#a865c9`
and regenerate PNGs
tnx!!!!!!!

**Comment by notofir** [comment]
Changed [color_legend.tsv](https://console.cloud.google.com/storage/browser/_details/gnlp.bursteinlab.org/data/color_legend.tsv?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&project=genomic-nlp) and [model_data.pkl](https://console.cloud.google.com/storage/browser/_details/gnlp.bursteinlab.org/data/model_data.pkl?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&project=genomic-nlp)

**Comment by dudubur** [comment]
looks great!
@notofir  == king 👑

**Comment by dudubur** [comment]
resolved by commit 4551312
