### ISSUE TITLE
Clear search mode and value after selecting point

### ISSUE THREAD

**Issue by dudubur** [burstein-lab/genomic-nlp-server#311]
If you search and then select points the search keeps showing the value searched and the search mode.
It would be better to have the search mode reset and the search field hidden, as it is when the first thing you do is select a point by zooming in without a search:
![image](https://github.com/burstein-lab/genomic-nlp-server/assets/67689371/b0568cc1-adc7-4701-9a42-ff80c63a4327)

**Comment by notofir** [comment]
Resolved by #314
