### ISSUE TITLE
Functional category N/A after selecting point from NEIGHBOR graph

### ISSUE THREAD

**Issue by dudubur** [burstein-lab/genomic-nlp-server#321]
Choosing a visually easy example:
- Search for model word K07654.1
- open the NEIGHBOR graph
- hover over the first bar (closest neighbor, K07670.1)
- Tooltip says "Functional category: undefined" 
- Click on this first bar 
- Information panel reads above Functional category "N/A"
- select a different point
-  select manually K07670.1
- Information panel correctly reads above Functional category "Two-component system"

Meaning: when going through the NEIGHBOR graph something goes wrong with the "Functional category" field on the info panel.
@notofir

**Comment by notofir** [comment]
Resolved by #324
