### ISSUE TITLE
download results

### ISSUE THREAD

**Issue by daniellemiller** [burstein-lab/genomic-nlp-server#95]
following #94 - sequences_matches.tsv

1. load model_data as `df`
2. load sequences_matches.tsv from #94 as `matches`
3. rename `matches` first column to 'query' and the second column to 'word'.
4. merge `matches` with `df` by the 'word' column.
5. enable the user to download this table

**Comment by notofir** [comment]
There's already a download button :S

![image](https://user-images.githubusercontent.com/7872989/230770349-69a7d510-b439-47eb-8872-20a7e61954e7.png)
